### ISSUE TITLE
No output after running Start.bat

### ISSUE THREAD

**Issue by Svahnen** [gabrielbsin/Ellin#1]
I have installed JDK 8 and then tried tu run Start.bat, the cmd window then starts but shows no output and the server does not seem to be running since i cant connect using localhost.exe.

Is there any guide on how to make this server work?

**Comment by gabrielbsin** [comment]
Hello, I can create a video of how to run the server, if you want.

**Comment by AcezukyRockon** [comment]
Hello @gabrielbsin , sorry for bump into old issue, I also got same issue as Svahnen, no output on cmd window, do you have any idea what's wrong?

**Comment by AcezukyRockon** [comment]
Ah my bad, I created database wrong name. I created "leaderms", but it should be "leaderms2". Now Start.bat show stuffs and client works perfectly.

**Comment by AcezukyRockon** [comment]
Actually, I tried with Window 11, still get same no output terminal, i'm checking it again.
Welp, found it. It was because my mariadb is too new. I tested with Mariadb version 10.4.34 and java jdk1.8.0_271, it worked.
